use super::MenuLabels;

pub(super) const LABELS: MenuLabels = MenuLabels {
    app_name: "QingYu",
    file: "Arquivo",
    edit: "Editar",
    format: "Formatar",
    view: "Exibir",
    new_document: "Novo",
    open_document: "Abrir...",
    open_recent_file: "Abrir arquivo recente",
    no_recent_files: "Nenhum arquivo recente",
    clear_recent_files: "Limpar arquivos recentes",
    open_folder: "Alternar diretório de notas...",
    quick_open: "Abertura rapida...",
    close_document: "Fechar arquivo",
    save_document: "Salvar",
    save_document_as: "Salvar como...",
    sync_now: "Sincronizar agora",
    export: "Exportar",
    export_pdf: "Exportar PDF",
    export_html: "Exportar HTML",
    export_docx: "Exportar DOCX",
    export_epub: "Exportar EPUB",
    export_latex: "Exportar LaTeX",
    settings: "Configurações...",
    check_updates: "Verificar atualizações",
    undo: "Desfazer",
    redo: "Refazer",
    cut: "Recortar",
    copy: "Copiar",
    paste: "Colar",
    select_all: "Selecionar tudo",
    hide: "Ocultar QingYu",
    hide_others: "Ocultar outros",
    show_all: "Mostrar tudo",
    quit: "Encerrar QingYu",
    fullscreen: "Tela cheia",
    toggle_file_list: "Alternar lista de arquivos",
    toggle_all_folds: "Recolher/expandir tudo",
    toggle_read_only_mode: "Alternar modo somente leitura",
    toggle_source_mode: "Alternar modo fonte",
    bold: "Negrito",
    italic: "Itálico",
    strikethrough: "Tachado",
    inline_code: "Código embutido",
    paragraph: "Parágrafo",
    heading_1: "Título 1",
    heading_2: "Título 2",
    heading_3: "Título 3",
    bullet_list: "Lista com marcadores",
    ordered_list: "Lista numerada",
    quote: "Citação",
    code_block: "Bloco de código",
    link: "Link",
    image: "Imagem",
    import_local_images: "Importar imagens locais...",
    import_local_files: "Importar arquivos locais...",
    table: "Tabela",
};
