// 由 scripts/generateCodeLanguages.cjs 根据内置 Highlight.js 资源生成，请勿手动编辑。
export const BUNDLED_CODE_LANGUAGES = [
    "1c", "abap", "abnf", "accesslog", "actionscript", "ada", "angelscript", "apache",
    "applescript", "arcade", "arduino", "armasm", "asciidoc", "aspectj", "autohotkey", "autoit",
    "avrasm", "awk", "axapta", "bash", "basic", "bnf", "brainfuck", "c",
    "cal", "capnproto", "ceylon", "clean", "clojure", "clojure-repl", "cmake", "coffeescript",
    "coq", "cos", "cpp", "crmsh", "crystal", "csharp", "csp", "css",
    "d", "dart", "delphi", "diff", "django", "dns", "dockerfile", "dos",
    "dsconfig", "dts", "dust", "ebnf", "elixir", "elm", "erb", "erlang",
    "erlang-repl", "excel", "fix", "flix", "fortran", "fsharp", "gams", "gauss",
    "gcode", "gdscript", "gherkin", "glsl", "gml", "go", "golo", "gradle",
    "graphql", "groovy", "haml", "handlebars", "haskell", "haxe", "hlsl", "hsp",
    "http", "hy", "inform7", "ini", "irpf90", "isbl", "java", "javascript",
    "jboss-cli", "json", "julia", "julia-repl", "kotlin", "lasso", "latex", "ldif",
    "leaf", "less", "lisp", "livecodeserver", "livescript", "llvm", "lsl", "lua",
    "makefile", "markdown", "mathematica", "matlab", "maxima", "mel", "mercury", "mipsasm",
    "mizar", "mlir", "mojolicious", "monkey", "moonbit", "moonscript", "n1ql", "nestedtext",
    "nginx", "nim", "nix", "node-repl", "nsis", "objectivec", "ocaml", "openscad",
    "oxygene", "parser3", "perl", "pf", "pgsql", "php", "php-template", "plaintext",
    "pony", "powershell", "processing", "profile", "prolog", "properties", "protobuf", "puppet",
    "purebasic", "python", "python-repl", "q", "qml", "r", "reasonml", "rib",
    "roboconf", "routeros", "rsl", "ruby", "ruleslanguage", "rust", "sas", "scala",
    "scheme", "scilab", "scss", "shell", "smali", "smalltalk", "sml", "solidity",
    "sqf", "sql", "stan", "stata", "step21", "stylus", "subunit", "swift",
    "taggerscript", "tap", "tcl", "template", "thrift", "tp", "twig", "typescript",
    "vala", "vbnet", "vbscript", "vbscript-html", "verilog", "vhdl", "vim", "wasm",
    "wren", "x86asm", "xl", "xml", "xquery", "yaml", "yul", "zephir",
] as const;
